### ISSUE TITLE
Update CI to also run on pull requests

### ISSUE THREAD

**Issue by vikaspotluri123** [gradebook/school-configuration#9]
- [x] on push to master, pr
```yaml
# I pulled this from a different project
on:
  push:
    branches:
      - master
  pull_request: {}
```
- [x] only run deploy for push to master
  - Check out the code blocks around [this area](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-contexts) of the docs

- [x] Modify https://github.com/gradebook/school-configuration/blob/7e2445e01b481a89245adb27f704f41828f4ca95/.github/workflows/deploy.yml#L10 to always return true for pull requests

- [x] Don't push this directly to master, create a PR 😄
